all: a1 a2 a3 a5 a6 a8


a1:
	g++ 1/main.cpp -o 1.out

a2:
	g++ 2/main.cpp -o 2.out

a3:
	g++ 3/main.cpp -o 3.out

a5:
	g++ 5/main.cpp -o 5.out

a6:
	g++ 6/main.cpp -o 6.out

a8:
	g++ 8/main.cpp -o 8.out

